[target.riscv64imac-unknown-none-elf]
linker = "riscv64-unknown-elf-gcc"
rustflags = [
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=-static",
    "-C", "link-arg=-T/home/acane/Desktop/xv6-riscv/user/user.ld",
    "-C", "panic=abort",
]

[build]
target = "riscv64imac-unknown-none-elf"